# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('api_name', models.CharField(max_length=20, null=True)),
                ('api_protocol', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=50, null=True)),
                ('api_type', models.CharField(max_length=20, null=True)),
                ('api_desc', models.TextField(null=True)),
                ('api_param', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=20, null=True)),
                ('pro_id', models.IntegerField(null=True)),
                ('api_id', models.IntegerField(null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('input_data', models.TextField(null=True)),
                ('exp_data', models.TextField(null=True)),
                ('check_type', models.IntegerField(null=True)),
                ('case_desc', models.TextField(null=True)),
                ('is_set', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('suite_id', models.IntegerField(null=True)),
                ('case_id', models.IntegerField(null=True)),
                ('api_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('env_name', models.CharField(max_length=20, null=True)),
                ('env_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('model_name', models.CharField(max_length=20, null=True)),
                ('model_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100, null=True)),
                ('pro_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_id', models.IntegerField(null=True)),
                ('opt_duration', models.IntegerField(null=True)),
                ('pass_num', models.IntegerField(null=True)),
                ('fail_num', models.IntegerField(null=True)),
                ('apt_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(null=True)),
                ('case_id', models.IntegerField(null=True)),
                ('api_id', models.IntegerField(null=True)),
                ('input_data', models.TextField(null=True)),
                ('out_data', models.TextField(null=True)),
                ('exp_data', models.TextField(null=True)),
                ('is_pass', models.BooleanField()),
                ('case_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('suite_name', models.CharField(max_length=20, null=True)),
                ('suite_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('var_name', models.CharField(max_length=20, null=True)),
                ('var_type', models.CharField(max_length=20, null=True)),
                ('var_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('var_id', models.IntegerField(null=True)),
                ('env_id', models.IntegerField(null=True)),
                ('var_value', models.TextField(null=True)),
            ],
        ),
    ]
