# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100, null=True)),
                ('pro_desc', models.TextField(null=True)),
            ],
        ),
    ]
