# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('env_name', models.CharField(max_length=20, null=True)),
                ('env_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('env_id', models.IntegerField(null=True)),
                ('var_name', models.CharField(max_length=20, null=True)),
                ('var_type', models.CharField(max_length=20, null=True)),
                ('var_value', models.TextField(null=True)),
                ('var_desc', models.TextField(null=True)),
            ],
        ),
    ]
