# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0003_varsevn'),
    ]

    operations = [
        migrations.AddField(
            model_name='varsevn',
            name='var_env_id',
            field=models.IntegerField(null=True),
        ),
    ]
