# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0004_varsevn_var_env_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_id', models.IntegerField(null=True)),
                ('var_value', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vars',
            name='var_value',
        ),
        migrations.RemoveField(
            model_name='varsevn',
            name='var_env_id',
        ),
    ]
