# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0005_auto_20160910_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vars',
            name='env_id',
        ),
        migrations.AddField(
            model_name='varvalue',
            name='env_id',
            field=models.IntegerField(null=True),
        ),
    ]
