# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0006_auto_20160910_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='varvalue',
            name='pro_id',
            field=models.IntegerField(null=True),
        ),
    ]
