# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0007_varvalue_pro_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VarsEvn',
        ),
    ]
