# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0008_delete_varsevn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('api_name', models.CharField(max_length=20, null=True)),
                ('api_protocol', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=50, null=True)),
                ('api_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('model_name', models.CharField(max_length=20, null=True)),
                ('model_desc', models.TextField(null=True)),
            ],
        ),
    ]
