# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0010_proapi_api_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('api_name', models.CharField(max_length=20, null=True)),
                ('api_protocol', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=50, null=True)),
                ('api_type', models.CharField(max_length=20, null=True)),
                ('api_desc', models.TextField(null=True)),
                ('api_param', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(null=True)),
                ('suite_id', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('input_type', models.CharField(max_length=20, null=True)),
                ('input_data', models.CharField(max_length=20, null=True)),
                ('exp_data', models.TextField(null=True)),
                ('check_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProModel',
            new_name='Model',
        ),
        migrations.DeleteModel(
            name='ProApi',
        ),
    ]
