# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0013_auto_20160912_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('suite_id', models.IntegerField(null=True)),
                ('case_id', models.IntegerField(null=True)),
            ],
        ),
    ]
