# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0014_casesuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_desc',
            field=models.TextField(null=True),
        ),
    ]
