# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0016_remove_case_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='suite_id',
        ),
    ]
