# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0017_remove_case_suite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='input_type',
        ),
    ]
