# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0019_case_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesuite',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
