# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0020_casesuite_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pro_id',
            field=models.IntegerField(null=True),
        ),
    ]
