# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0022_case_case_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesuite',
            name='model_id',
        ),
    ]
