# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0023_remove_casesuite_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_set',
            field=models.IntegerField(null=True),
        ),
    ]
